kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-test
allowPrivilegedContainer: true
runAsUser:
  type: MustRunAsNonRoot 
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- my-admin-user
groups:
- my-admin-group
